name: ProMeta
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cpp-expected=1.3.1=h171cf75_0
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - double-conversion=3.3.1=h5888daf_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=8.0.0=gpl_h5c0ada0_706
  - fmt=12.0.0=h2b0788b_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=12.1.0=h15599e2_0
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - icu=75.1=he02047a_0
  - imath=3.2.2=hde8ca8f_0
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - jasper=4.2.8=he3c4edf_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.25.2=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.2=gpl_h7be2006_100
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=38_h0358290_openblas
  - libclang-cpp21.1=21.1.4=default_h99862b1_0
  - libclang13=21.1.4=default_h746c552_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_6
  - libgcc-ng=15.2.0=h69a702a_6
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.1=h32235b2_1
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_6
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=hf08fa70_5
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblapacke=3.9.0=38_h6ae95b6_openblas
  - libllvm21=21.1.4=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmamba=2.3.3=h09abcb8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.0=h5eee18b_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libopencv=4.12.0=qt6_py310hdb0ca46_607
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h49aed37_2
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsolv=0.7.35=h9463b59_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_6
  - libstdcxx-ng=15.2.0=h4852527_6
  - libsystemd0=257.9=h996ca69_0
  - libtiff=4.7.1=h8261f1e_0
  - libudev1=257.9=h085a93f_0
  - libunistring=0.9.10=h7f98852_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.12.3=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - mamba=2.3.3=h4396525_2
  - mpg123=1.32.9=hc50e24c_0
  - ncurses=6.5=h7934f7d_0
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=qt6_py310hec850f8_607
  - openexr=3.4.2=hfb145c2_1
  - openh264=2.6.0=hc22cd8d_0
  - openjph=0.25.0=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.4=h26f9b46_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a8bead_2
  - py-opencv=4.12.0=qt6_py310h89973df_607
  - python=3.10.12=hd12c33a_0_cpython
  - python_abi=3.10=2_cp310
  - qt6-main=6.9.3=h5c1c036_1
  - rav1e=0.7.1=h8fae777_3
  - readline=8.3=hc2a1206_0
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - s_gd2=1.8.1=py310h03d9f68_5
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.26=h68140b3_0
  - setuptools=80.9.0=py310h06a4308_0
  - shaderc=2025.4=h3e344bc_0
  - simdjson=4.0.7=hb700be7_0
  - snappy=1.2.2=h03e3b7b_0
  - spirv-tools=2025.4=hb700be7_0
  - sqlite=3.50.2=hb25bd0a_1
  - svt-av1=3.1.2=hecca717_0
  - tbb=2022.3.0=h8d10470_0
  - tk=8.6.15=h54e0aa7_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml-cpp=0.8.0=h3f2d84a_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - adjusttext==1.3.0
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anndata==0.10.9
      - annotated-types==0.7.0
      - anyio==4.11.0
      - arboreto==0.1.6
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - array-api-compat==1.12.0
      - arrow==1.4.0
      - arviz==0.22.0
      - asciitree==0.3.3
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - biopython==1.86
      - bleach==6.3.0
      - blitzgsea==1.3.54
      - bokeh==3.8.0
      - boltons==25.0.0
      - botocore==1.40.65
      - cellrank==2.0.7
      - certifi==2025.10.5
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - chex==0.1.90
      - choreographer==1.2.1
      - click==8.3.0
      - cloudpickle==3.1.2
      - colorcet==3.1.0
      - combat==0.3.3
      - comm==0.2.3
      - contourpy==1.2.1
      - ctxcore==0.2.0
      - cupy-cuda12x==13.6.0
      - custom-inherit==2.4.1
      - cycler==0.12.1
      - cykhash==2.0.1
      - cython==3.2.1
      - cytoolz==1.1.0
      - dask==2024.8.1
      - dask-expr==1.1.11
      - dask-image==2024.5.3
      - datashader==0.18.2
      - datetime==5.5
      - debugpy==1.8.17
      - decorator==5.2.1
      - decoupler==2.1.1
      - deepcomparer==0.4.0
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - diffrax==0.7.0
      - dill==0.4.0
      - distlib==0.4.0
      - distributed==2024.11.2
      - distro==1.9.0
      - docrep==0.3.2
      - docstring-inheritance==3.0.0
      - dunamai==1.25.0
      - dynamo-release==1.4.1
      - einops==0.8.1
      - entmax==1.3
      - equinox==0.13.2
      - et-xmlfile==2.0.0
      - ete3==3.1.3
      - etils==1.13.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fa2-modified==0.4
      - faiss-gpu==1.7.2
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - fastrlock==0.8.3
      - fbpca==1.0
      - filelock==3.20.0
      - flax==0.10.7
      - fonttools==4.60.1
      - formulaic==1.2.1
      - formulaic-contrasts==1.0.0
      - fqdn==1.5.1
      - frozendict==2.4.6
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - future==1.0.0
      - gdown==5.2.0
      - geopandas==1.1.1
      - get-version==3.5.5
      - gitdb==4.0.12
      - gitpython==3.1.45
      - graphtools==2.1.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5netcdf==1.7.3
      - h5py==3.15.1
      - harmonypy==0.0.10
      - hf-xet==1.2.0
      - hmmlearn==0.3.3
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanize==4.14.0
      - identify==2.6.15
      - idna==3.11
      - igraph==1.0.0
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - iniconfig==2.3.0
      - interface-meta==1.3.0
      - interlap==0.2.7
      - intervaltree==3.1.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jax==0.6.2
      - jax-cuda12-pjrt==0.6.2
      - jax-cuda12-plugin==0.6.2
      - jaxlib==0.6.2
      - jaxopt==0.8.5
      - jaxtyping==0.3.3
      - jedi==0.19.2
      - jinja2==3.0.3
      - jiter==0.11.1
      - jmespath==1.0.1
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - k3d==2.17.0
      - kaleido==1.2.0
      - kiwisolver==1.4.9
      - ktplotspy==0.3.3
      - lamin-utils==0.15.0
      - lark==1.3.1
      - lazy-loader==0.4
      - legacy-api-wrap==1.5
      - legendkit==0.3.6
      - leidenalg==0.11.0
      - libpysal==4.13.0
      - lifelines==0.30.0
      - lightning==2.5.5
      - lightning-utilities==0.15.2
      - lineax==0.0.8
      - llvmlite==0.45.1
      - locket==1.0.0
      - logistro==2.0.1
      - loguru==0.7.3
      - loompy==3.0.8
      - lz4==4.4.5
      - macs3==3.0.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marsilea==0.5.6
      - matplotlib==3.8.4
      - matplotlib-inline==0.2.1
      - matplotlib-scalebar==0.9.0
      - mdurl==0.1.2
      - mellon==1.6.1
      - memento-de==0.1.2
      - metatime==1.3.0
      - mistune==3.1.4
      - mizani==0.14.3
      - ml-collections==1.1.0
      - ml-dtypes==0.5.3
      - mofax==0.3.7
      - more-itertools==10.8.0
      - moscot==0.4.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mudata==0.3.2
      - multidict==6.7.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.18
      - multiprocessing-on-dill==3.5.0a4
      - multiscale-spatial-image==2.0.2
      - muon==0.1.7
      - narwhals==2.10.1
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - ncls==0.0.70
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nltk==3.9.2
      - nodeenv==1.9.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numcodecs==0.13.1
      - numdifftools==0.9.41
      - numexpr==2.14.1
      - numpy==1.26.4
      - numpy-groupies==0.11.3
      - numpyro==0.19.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.4.127
      - ome-zarr==0.11.1
      - omicverse==1.7.8
      - omnipath==1.0.12
      - openai==2.7.1
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.6
      - optimistix==0.0.11
      - orbax-checkpoint==0.11.26
      - orjson==3.11.4
      - ott-jax==0.5.2
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.1.1
      - pandocfilters==1.5.1
      - param==2.2.1
      - parse==1.20.2
      - parso==0.8.5
      - partd==1.4.2
      - patsy==1.0.2
      - pertpy==0.10.0
      - pexpect==4.9.0
      - pillow==12.0.0
      - pims==0.7
      - platformdirs==4.5.0
      - plotly==5.24.1
      - plotnine==0.15.1
      - pluggy==1.6.0
      - ply==3.11
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - pooch==1.8.2
      - pot==0.9.6.post1
      - pre-commit==4.3.0
      - progressbar2==4.5.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pubchempy==1.0.5
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pybedtools==0.10.0
      - pybigwig==0.3.24
      - pycirclize==1.10.1
      - pycparser==2.23
      - pyct==0.6.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydeseq2==0.5.2
      - pyfaidx==0.7.2.2
      - pygam==0.10.1
      - pygments==2.19.2
      - pygpcca==1.0.4
      - pygsp==0.6.1
      - pymde==0.2.3
      - pynndescent==0.5.13
      - pynvml==13.0.1
      - pyogrio==0.11.1
      - pyomo==6.9.5
      - pyparsing==3.2.5
      - pypng==0.20220715.0
      - pyproj==3.7.1
      - pyranges==0.1.4
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pysam==0.23.3
      - pyscenic==0.12.1
      - pysocks==1.7.1
      - pytest==9.0.1
      - pytest-timeout==2.4.0
      - python-dateutil==2.9.0.post0
      - python-dotplot==0.0.1
      - python-json-logger==4.0.0
      - python-utils==3.9.1
      - pytorch-ignite==0.5.3
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - reportlab==4.4.4
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - rustworkx==0.17.1
      - s3fs==0.4.2
      - safetensors==0.6.2
      - scanpy==1.11.5
      - scglue==0.4.0
      - scikit-image==0.22.0
      - scikit-learn==1.4.2
      - scikit-misc==0.5.2
      - scipy==1.11.3
      - scvelo==0.3.3
      - scvi-colab==0.13.0
      - scvi-tools==1.3.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.43.0
      - session-info==1.0.1
      - session-info2==0.2.3
      - shapely==2.1.2
      - simplejson==3.20.2
      - six==1.17.0
      - slicerator==1.1.0
      - smmap==5.0.2
      - snapatac2==2.8.0
      - sniffio==1.3.1
      - sorted-nearest==0.0.41
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - sparse==0.17.0
      - sparsecca==0.3.1
      - spatial-image==1.2.1
      - spatialdata==0.3.0
      - squidpy==1.6.5
      - stack-data==0.6.3
      - starnet==1.0.0
      - statsmodels==0.14.5
      - stdlib-list==0.12.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tangram-sc==1.0.4
      - tasklogger==1.2.0
      - tblib==3.2.1
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorstore==0.1.78
      - termcolor==3.2.0
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - toolz==1.1.0
      - torch==2.6.0
      - torch-geometric==2.7.0
      - torchaudio==2.6.0
      - torchdr==0.3
      - torchmetrics==1.8.2
      - torchvision==0.21.0
      - tornado==6.5.2
      - toyplot==2.0.0
      - toytree==3.0.10
      - tqdm==4.67.1
      - traitlets==5.14.3
      - traittypes==0.2.3
      - transformers==4.57.1
      - treescope==0.1.10
      - triton==3.2.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uv==0.9.7
      - validators==0.35.0
      - virtualenv==20.35.4
      - wadler-lindig==0.1.7
      - wandb==0.22.3
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - wrapt==2.0.0
      - xarray==2024.11.0
      - xarray-dataclasses==1.9.1
      - xarray-einstats==0.8.0
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - xgboost==3.1.2
      - xxhash==3.6.0
      - xyzservices==2025.10.0
      - yarl==1.22.0
      - zarr==2.17.1
      - zict==3.0.0
      - zipp==3.23.0
      - zope-interface==8.0.1
prefix: /home/dataset-assist-0/yaosen/conda_envs/ProMeta
